---
- name: Create a new alicloud VPC resource
  ali_vpc:
    cidr_block: '{{ vpc_cidr }}'
    vpc_name: '{{ vpc_name }}'
    description: '{{ vpc_description }}'
  register: vpc

- name: Get the existing vpc
  ali_vpc_info:
    name_prefix: '{{vpc_name}}'
  register: vpcs