---
- name: Create a new alicloud VPC resource
  alibaba.alicloud.ali_vpc:
    alicloud_region: '{{ alicloud_region }}'
    cidr_block: '{{ vpc_cidr }}'
    vpc_name: '{{ vpc_name }}'
    description: '{{ vpc_description }}'
  register: vpc

- name: Get the existing vpc
  alibaba.alicloud.ali_vpc_info:
    alicloud_region: '{{ alicloud_region }}'
    name_prefix: '{{vpc_name}}'
  register: vpcs