---
- name: Creating a public SLB instance
  ali_slb_lb:
    name: '{{ slb_name }}-public'
    internet_charge_type: '{{ internet_charge_type }}'
    is_internet: True
    spec: slb.s1.small
  register: slbpub

- name: Creating a private SLB instance
  ali_slb_lb:
    name: '{{ slb_name }}-private'
    internet_charge_type: '{{ internet_charge_type }}'
    spec: slb.s1.small
    vswitch_id: '{{ vswitches.vswitches.0.id }}'
  register: slbpri

- name: Filter slb using name_regex
  ali_slb_lb_info:
    name_prefix: '{{ slb_name }}'
  register: slbs

- name: Changed. Add slb tags.
  ali_slb_tag:
    resource_type: 'instance'
    resource_ids: '{{ slbs.ids }}'
    tags: '{{ slb_tags }}'
