# This Playbook contains test scenario for vpc
# Playbook created by : Shrutika M

- name: Create VPC
  hosts: localhost
  connection: local
  vars:
    # create vpc
    alicloud_region: cn-beijing
    state: present
    stateDel: absent
    cidr_block: 10.0.0.0/8
    vpc_name: travis-ansible-vpc
    description: travis-ansible-vpc
    # create vswitch
    vsw_cidr: 10.0.13.0/24
    vsw_name: Test_Vswitch
    alicloud_zone: cn-beijing-a
    vsw_description: Test vswitch created

    # Eip Realted interface
    internetChargeType: PayByTraffic
    bandwidth: 5
    new_bandwidth: 7

    # create ecs instance connected to the switch
    image: ubuntu_14_0405_64_40G_base_20170222.vhd
    type: ecs.n4.small
    instance_name: travis-ansible-vpc-instance
    host_name: myhost
    password: pass@123
    count: 1
    allocate_public_ip: False
    pagenumber: 1
    pagesize: 10

    # create route entry
    destination_cidrblock: 10.0.14.0/24

  tasks:
    - name: Create VPC
      alicloud_vpc:
        alicloud_region: '{{ alicloud_region }}'
        state: '{{ state }}'
        cidr_block: '{{ cidr_block }}'
        vpc_name: '{{ vpc_name }}'
        description: '{{ description }}'
      register: create_vpc
    - debug: var=create_vpc

    # Querying vpc list with all valid parameters
    - name: Querying vpc
      alicloud_vpc:
       alicloud_region: '{{ alicloud_region }}'
       vpc_id: '{{ create_vpc["vpc_id"] }}'
       state: list
      register: query_vpc_result
    - debug: var=query_vpc_result

    # Create Vswitch
    - name: Create VSwitch
      alicloud_vswitch:
        alicloud_region: '{{ alicloud_region }}'
        alicloud_zone: '{{ alicloud_zone }}'
        state: '{{ state }}'
        cidr_block: '{{ vsw_cidr }}'
        vswitch_name: '{{ vsw_name }}'
        description: '{{ description }}'
        vpc_id: '{{ create_vpc["vpc_id"] }}'
      register: create_vsw
    - debug: var=create_vsw

    # Querying vswitch list with vpc_id
    - name: Querying vswitch
      alicloud_vswitch:
       alicloud_region: '{{ alicloud_region }}'
       vpc_id: '{{ create_vpc["vpc_id"] }}'
       state: list
      register: query_vsw
    - debug: var=query_vsw

     # Querying vswitch list with vswitch_ids
    - name: Querying vswitch
      alicloud_vswitch:
       alicloud_region: '{{ alicloud_region }}'
       vswitch_id: '{{ create_vsw["vswitch_id"] }}'
       state: list
      register: query_vsw_2
    - debug: var=query_vsw_2

    - name: Creating an ECS instance
      ecs:
        alicloud_region: '{{ alicloud_region }}'
        alicloud_zone: '{{ alicloud_zone }}'
        image: '{{ image }}'
        type: '{{ type }}'
        instance_name: '{{ instance_name }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        count: '{{ count }}'
        allocate_public_ip: '{{ allocate_public_ip }}'
        vswitch_id: '{{ create_vsw["vswitch_id"] }}'
      register: create_instance_result
    - debug: var=create_instance_result

    # create route entry
    - name: Create route entry
      alicloud_route_entry:
        alicloud_region: '{{ alicloud_region }}'
        state: '{{ state }}'
        nexthop_id: '{{ create_instance_result["instance_ids"][0] }}'
        router_id: '{{ create_vpc["vpc"]["router_id"] }}'
        destination_cidrblock: '{{ destination_cidrblock }}'
      register: create_route_entry
    - debug: var=create_route_entry

    # Querying route entry list with all valid parameters
    - name: Querying vrouter list
      alicloud_route_entry:
       alicloud_region: '{{ alicloud_region }}'
       router_id: '{{ create_vpc["vpc"]["router_id"] }}'
       state: list
      register: query_vrouter_result
    - debug: var=query_vrouter_result

#    - name: Request EIP with all parameters
#      ecs_eip:
#       alicloud_region: '{{ alicloud_region }}'
#       bandwidth: '{{ bandwidth }}'
#       internet_charge_type: '{{ internetChargeType }}'
#      register: req_eip_result
#    - debug: var=req_eip_result
#
#
#    - name: Modify EIP with all parameters
#      ecs_eip:
#       alicloud_region: '{{ alicloud_region }}'
#       bandwidth: '{{ new_bandwidth }}'
#       allocation_id: '{{ req_eip_result.result["AllocationId"] }}'
#      register: modify_eip
#    - debug: var=modify_eip
#
#    - name: Binding EIP with all parameters
#      ecs_eip:
#       alicloud_region: '{{ alicloud_region }}'
#       state: join
#       instance_id: '{{ create_instance_result.result[0].instance_id }}'
#       allocation_id: '{{ req_eip_result.result["AllocationId"] }}'
#      register: bind_eip_result
#    - debug: var=bind_eip_result
#
#    - pause:
#        seconds: 15
#
#    - name: Unbinding EIP with all parameters
#      ecs_eip:
#       alicloud_region: '{{ alicloud_region }}'
#       state: leave
#       instance_id: '{{ create_instance_result.result[0].instance_id }}'
#       allocation_id: '{{ req_eip_result.result["AllocationId"] }}'
#      register: unbind_eip_result
#    - debug: var=unbind_eip_result
#
#    - pause:
#        seconds: 15
#
#    - name: Release EIP with all parameters
#      ecs_eip:
#       alicloud_region: '{{ alicloud_region }}'
#       state: absent
#       allocation_id: '{{ req_eip_result.result["AllocationId"] }}'
#      register: release_eip_result
#    - debug: var=release_eip_result

    - name: Delete route entry
      alicloud_route_entry:
        alicloud_region: '{{ alicloud_region }}'
        state: absent
        destination_cidrblock: '{{ create_route_entry["destination_cidrblock"] }}'
        nexthop_id: '{{ create_instance_result["instance_ids"][0]}}'
        router_id: '{{ create_vpc["vpc"]["router_id"] }}'
      register: delete_route_entry
    - debug: var=delete_route_entry
#
    - name: Delete ECS Instance
      alicloud_instance:
        alicloud_region: '{{ alicloud_region }}'
        instance_ids: '{{ create_instance_result["instance_ids"][0] }}'
        state: absent
      register: delete_instance_result
    - debug: var=delete_instance_result

    # Delete Vsitches with vpc_id and vswitch_ids
    - name: Delete Vswitch
      alicloud_vswitch:
        state: absent
        alicloud_region: '{{ alicloud_region }}'
        vpc_id: '{{ create_vpc["vpc_id"] }}'
        vswitch_id: '{{ create_vsw["vswitch_id"] }}'
      register: delete_vswitch_result
    - debug: var=delete_vswitch_result

    - name: Get Security Group Info
      alicloud_security_group:
        state: list
        alicloud_region: '{{ alicloud_region }}'
        vpc_id: '{{ create_vpc["vpc_id"] }}'
      register: security_group_result
    - debug: var=security_group_result

    - name: Delete Security Group
      alicloud_security_group:
        state: absent
        alicloud_region: '{{ alicloud_region }}'
        group_id: '{{ security_group_result["group_ids"][0] }}'
      register: delete_security_group_result
    - debug: var=delete_security_group_result

    - name: Delete VPC
      alicloud_vpc:
        alicloud_region: '{{ alicloud_region }}'
        vpc_id: '{{ create_vpc["vpc_id"] }}'
        state: '{{ stateDel }}'
      register: delete_vpc
    - debug: var=delete_vpc