# This Playbook contains test scenario for vpc
# Playbook created by : Guimin He

- name: Create VPC
  hosts: localhost
  connection: local
  vars:
    # create vpc
    alicloud_region: cn-beijing
    state: present
    stateDel: absent
    cidr_block: 10.0.0.0/8
    vpc_name: travis-ansible-vpc
    description: travis-ansible-vpc
    # create vswitch
    vsw_cidr: 10.0.13.0/24
    vsw_name: Test_Vswitch
    alicloud_zone: cn-beijing-a
    vsw_description: Test vswitch created

    # create group
    sg_name: travis-ansible-instance
    inboundRules:
      - proto: tcp
        port_range: 22/22
        cidr_ip: 0.0.0.0/0
        priority: 1

      - proto: tcp
        port_range: 80/80
        cidr_ip: 0.0.0.0/0
        priority: 1

      - proto: udp
        port_range: 10988/10989
        cidr_ip: 47.89.23.33/32
        priority: 2

    outboundRules:
      - proto: tcp
        port_range: 80/80
        cidr_ip: 192.168.0.54/32
        priority: 1

      - proto: tcp
        port_range: 8080/8085
        cidr_ip: 47.89.23.33/32
        priority: 1

      - proto: udp
        port_range: 10989/10997
        cidr_ip: 47.89.23.33/32
        priority: 2

    # Eip Realted interface
    internetChargeType: PayByTraffic
    bandwidth: 7

    # create ecs instance connected to the switch
    image: ubuntu_14_0405_64_40G_base_20170222.vhd
    type: ecs.n4.small
    instance_name: travis-ansible-vpc-instance
    host_name: myhost
    password: pass@123
    count: 1
    allocate_public_ip: False
    user_data: "#!/bin/sh\ncd /root\ntouch hahah\nwget http://wordpress.org/latest.tar.gz\n"

    # create route entry
    destination_cidrblock: 10.0.14.0/24

  tasks:
    - name: Create VPC
      ali_vpc:
        alicloud_region: '{{ alicloud_region }}'
        state: '{{ state }}'
        cidr_block: '{{ cidr_block }}'
        vpc_name: '{{ vpc_name }}'
        description: '{{ description }}'
      register: create_vpc
    - debug: var=create_vpc

    # Create Vswitch
    - name: Create VSwitch
      ali_vswitch:
        alicloud_region: '{{ alicloud_region }}'
        alicloud_zone: '{{ alicloud_zone }}'
        state: '{{ state }}'
        cidr_block: '{{ vsw_cidr }}'
        vswitch_name: '{{ vsw_name }}'
        description: '{{ description }}'
        vpc_id: '{{ create_vpc["vpc_id"] }}'
      register: create_vsw
    - debug: var=create_vsw

    - name: Creating security group
      ali_security_group:
        alicloud_region: '{{ alicloud_region }}'
        name: '{{ sg_name }}'
        description: '{{description}}'
        vpc_id: '{{ create_vpc.vpc_id }}'
        rules: '{{ inboundRules }}'
        rules_egress: '{{ outboundRules }}'
      register: createsgeresult
    - debug: var=createsgeresult

    - name: Creating an ECS instance
      ali_instance:
        alicloud_region: '{{ alicloud_region }}'
        image: '{{ image }}'
        type: '{{ type }}'
        instance_name: '{{ instance_name }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        count: '{{ count }}'
        group_id: '{{ createsgeresult.group_id }}'
        allocate_public_ip: '{{ allocate_public_ip }}'
        vswitch_id: '{{ create_vsw.vswitch_id }}'
        user_data: '{{ user_data }}'
      register: create_instance_result
    - debug: var=create_instance_result

    # create route entry
    - name: Create route entry
      ali_route_entry:
        alicloud_region: '{{ alicloud_region }}'
        state: '{{ state }}'
        nexthop_id: '{{ create_instance_result["instance_ids"][0] }}'
        router_id: '{{ create_vpc["vpc"]["router_id"] }}'
        destination_cidrblock: '{{ destination_cidrblock }}'
      register: create_route_entry
    - debug: var=create_route_entry

    - name: allocating an eip
      ali_eip:
        alicloud_region: '{{ alicloud_region }}'
        internet_charge_type: '{{ internetChargeType }}'
        bandwidth: '{{ bandwidth }}'
        ip_address: '47.93.2.116'
        state: present
      register: new_eip

    - name: associate the created EIP with an ECS instance
      ali_eip:
        alicloud_region: '{{ alicloud_region }}'
        bandwidth: '{{bandwidth}}'
        ip_address: '{{ new_eip.ip_address }}'
        instance_id: '{{ create_instance_result["instance_ids"][0] }}'
        state: present

    - name: disassociate the created EIP with an ECS instance
      ali_eip:
        alicloud_region: '{{ alicloud_region }}'
        bandwidth: '{{bandwidth}}'
        ip_address: '{{ new_eip.ip_address }}'
        instance_id: '{{ create_instance_result["instance_ids"][0] }}'
        state: absent

    - name: release the created EIP
      ali_eip:
        alicloud_region: '{{ alicloud_region }}'
        ip_address: '{{ new_eip.ip_address }}'
        state: absent

    - name: Delete route entry
      ali_route_entry:
        alicloud_region: '{{ alicloud_region }}'
        state: absent
        destination_cidrblock: '{{ create_route_entry["destination_cidrblock"] }}'
        nexthop_id: '{{ create_instance_result["instance_ids"][0]}}'
        router_id: '{{ create_vpc["vpc"]["router_id"] }}'
      register: delete_route_entry
    - debug: var=delete_route_entry
#
    - name: Delete ECS Instance
      ali_instance:
        alicloud_region: '{{ alicloud_region }}'
        instance_ids: '{{ create_instance_result["instance_ids"][0] }}'
        force: true
        state: absent

    # Delete Vsitches with vpc_id and vswitch_ids
    - name: Delete Vswitch
      ali_vswitch:
        state: absent
        alicloud_region: '{{ alicloud_region }}'
        vpc_id: '{{ create_vpc["vpc_id"] }}'
        vswitch_id: '{{ create_vsw["vswitch_id"] }}'

    - name: Delete Security Group
      ali_security_group:
        state: absent
        alicloud_region: '{{ alicloud_region }}'
        group_id: '{{ createsgeresult.group_id }}'

    - name: Delete VPC
      ali_vpc:
        alicloud_region: '{{ alicloud_region }}'
        vpc_id: '{{ create_vpc["vpc_id"] }}'
        state: '{{ stateDel }}'