---
- name: Create an alicloud vpc cluster using ansible-provider-alicloud
  hosts: localhost
  remote_user: root

  roles:
    - vpc
    - vswitch
    - security_group
    - ecs_instance
    - ecs_disk