---
- name: Destroy the existing alicloud vpc cluster
  hosts: localhost
  remote_user: root

  tasks:
    - name: Get the existing instances
      alibaba.alicloud.ali_instance_info:
        alicloud_region: '{{ region_id }}'
        alicloud_zone: '{{ zone_id }}'
        instance_names:
          - '{{ name }}'
      register: instances

    - name: Delete the existing instances
      alibaba.alicloud.ali_instance:
        alicloud_region: '{{ region_id }}'
        alicloud_zone: '{{ zone_id }}'
        instance_ids: '{{ instances.ids }}'
        force: true
        state: absent
      when: instances.ids

    - name: Get the existing disks
      alibaba.alicloud.ali_disk_info:
        alicloud_region: '{{ region_id }}'
        name_prefix: '{{ disk_name }}'
        filters:
          zone_id: '{{ zone_id }}'
      register: disks

    - name: Delete the existing disk 0
      alibaba.alicloud.ali_disk:
        alicloud_region: '{{ region_id }}'
        alicloud_zone: '{{ zone_id }}'
        disk_id: '{{ disks.disks.0.id }}'
        state: absent
      when: disks.disks

    - name: Delete the existing disk 1
      alibaba.alicloud.ali_disk:
        alicloud_region: '{{ region_id }}'
        alicloud_zone: '{{ zone_id }}'
        disk_id: '{{ disks.disks.1.id}}'
        state: absent
      when: disks.disks

    - name: Get the existing vpc
      alibaba.alicloud.ali_vpc_info:
        alicloud_region: '{{ region_id }}'
        vpc_name: '{{ name }}'
      register: vpcs

    - name: Get the existing groups
      alibaba.alicloud.ali_security_group_info:
        alicloud_region: '{{ region_id }}'
        filters:
          vpc_id: '{{vpcs.vpcs.0.id}}'
      when: vpcs.vpcs
      register: sgs

    - name: Delete the existing security groups
      alibaba.alicloud.ali_security_group:
        alicloud_region: '{{ region_id }}'
        group_name: '{{ name }}'
        state: absent
      when: sgs.ids

    - name: Get the existing vswitches
      alibaba.alicloud.ali_vswitch_info:
        alicloud_region: '{{ region_id }}'
        filters:
          vpc_id: '{{vpcs.vpcs.0.id}}'
      when: vpcs.vpcs
      register: vsws

    - name: Delete the existing vswitch
      alibaba.alicloud.ali_vswitch:
        alicloud_region: '{{ region_id }}'
        alicloud_zone: '{{ zone_id }}'
        cidr_block: '{{ vswitch_cidr }}'
        vpc_id: '{{vpcs.vpcs.0.id}}'
        state: absent
      when: vsws.vswitches

    - name: Delete the existing vpc
      alibaba.alicloud.ali_vpc:
        alicloud_region: '{{ region_id }}'
        vpc_name: '{{ name }}'
        cidr_block: '{{ vpc_cidr }}'
        state: absent
      when: vpcs.vpcs