---
- name: Create an alicloud vpc cluster using ansible-provider-alicloud
  hosts: localhost
  remote_user: root

  tasks:
    - name: get all instecs
      alibaba.alicloud.ali_instance_info:
        alicloud_region: '{{ region_id }}'
      register: all_instance
