---
- name: Create a new alicloud VSwitch resource
  alibaba.alicloud.ali_vswitch:
    alicloud_region: '{{ region_id }}'
    alicloud_zone: '{{ zone_id }}'
    cidr_block: '{{ vswitch_cidr }}'
    vswitch_name: '{{ name }}'
    description: '{{ vswitch_description }}'
    vpc_id: '{{vpc.vpc.id}}'
  register: vswitch

- name: Get the existing vswitch
  alibaba.alicloud.ali_vswitch_info:
    alicloud_region: '{{ region_id }}'
    name_prefix: '{{ name }}'
    filters:
      vpc_id: '{{vpc.vpc.id}}'
  register: vswitches