---
- name: Get the existing vpc
  ali_vpc_facts:
    region: '{{alicloud_region}}'
    vpc_name: '{{vpc_name}}'
  register: vpcs

- name: Create a new alicloud VSwitch resource
  ali_vswitch:
    alicloud_region: '{{ alicloud_region }}'
    alicloud_zone: '{{ alicloud_zone }}'
    state: 'present'
    cidr_block: '{{ vswitch_cidr }}'
    vswitch_name: '{{ vswitch_name }}'
    description: '{{ vswitch_description }}'
    vpc_id: '{{vpcs.vpcs.0.id}}'
  register: vswitch
