---
- name: Create a new alicloud VPC resource
  alibaba.alicloud.ali_vpc:
    alicloud_region: '{{ region_id }}'
    state: 'present'
    cidr_block: '{{ vpc_cidr }}'
    vpc_name: '{{ name }}'
    description: '{{ vpc_description }}'
  register: vpc

- name: Get the existing vpc
  alibaba.alicloud.ali_vpc_info:
    alicloud_region: '{{ region_id }}'
    name_prefix: '{{ name }}'
  register: vpcs