---
- name: Get the existing ECS instances
  alibaba.alicloud.ali_instance_info:
    name_prefix: '{{ instance_name }}'
    filters:
      vpc_id: '{{ vpcs.vpcs.0.id }}'
  register: instances

- name: Creating two ECS instances
  alibaba.alicloud.ali_instance:
    image: '{{ image_id }}'
    type: '{{ instance_type }}'
    instance_name: '{{ item.1 }}'
    description: '{{ instance_description }}'
    host_name: '{{ host_name }}'
    password: '{{ password }}'

    allocate_public_ip: '{{ allocate_public_ip }}'
    internet_charge_type: '{{ internet_charge_type }}'
    max_bandwidth_in: '{{ max_bandwidth_in }}'
    max_bandwidth_out: '{{ max_bandwidth_out }}'

    security_groups: ['{{ sgs.groups.0.id }}']
    vswitch_id: '{{ item.0.id }}'

    system_disk_category: '{{ system_disk_category }}'
    system_disk_size: '{{ system_disk_size }}'
    count: '{{ number_of_instances }}'
    tags: '{{ instance_tags }}'
  with_together:
    - '{{ vswitches.vswitches }}'
    - '{{ instance_name }}'