---
- name: Create a VPC security group
  ali_security_group:
    name: '{{ security_group_name }}'
    description: '{{ group_description }}'
    vpc_id: '{{vpc.vpc.id}}'
    rules: '{{ group_inboundRules }}'
    rules_egress: '{{ group_outboundRules }}'
  register: group

- name: Get the existing groups
  ali_security_group_info:
    name_prefix: '{{ security_group_name }}'
  register: sgs
