---
- name: Create a VPC security group
  alibaba.alicloud.ali_security_group:
    alicloud_region: '{{ alicloud_region }}'
    name: '{{ security_group_name }}'
    description: '{{ group_description }}'
    vpc_id: '{{vpc.vpc.id}}'
    rules: '{{ group_inboundRules }}'
    rules_egress: '{{ group_outboundRules }}'
  register: group

- name: Get the existing groups
  alibaba.alicloud.ali_security_group_info:
    alicloud_region: '{{ alicloud_region }}'
    name_prefix: '{{ security_group_name }}'
  register: sgs
